# Generated by Django 4.0.1 on 2022-06-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='locationes',
            field=models.CharField(choices=[('indore', 'indore'), ('banglor', 'banglor'), ('remote', 'remote')], max_length=435, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualifications',
            field=models.CharField(choices=[('b.tech', 'b.tech')], max_length=435, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.language'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='link',
            field=models.CharField(max_length=235, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='locati',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.location'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='name',
            field=models.CharField(max_length=235, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.qualification'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java'), ('c++', 'c++')], max_length=435, null=True),
        ),
    ]
