# Generated by Django 4.0.1 on 2022-06-26 08:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_location_name_remove_qualification_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobsdis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imformation', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='movee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='pakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(max_length=3434352, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationes',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=334, null=True),
        ),
        migrations.DeleteModel(
            name='Joblist',
        ),
        migrations.DeleteModel(
            name='language',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.AddField(
            model_name='jobsdis',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.location'),
        ),
        migrations.AddField(
            model_name='jobsdis',
            name='pakages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.pakage'),
        ),
    ]
