# Generated by Django 4.0.1 on 2022-06-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_jobsdis_movee_pakage_remove_location_locationes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movee',
            name='lik',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pakage',
            name='limit',
            field=models.CharField(choices=[('1L TO 2L', '1L TO 2L'), ('2L TO 3L', '2L TO 3L'), ('3L TO 5L', '3L TO 5L'), ('5L TO 7L', '5L TO 7L'), ('7L TO 75L', '7L TO 75L')], max_length=3434352, null=True),
        ),
    ]
