# Generated by Django 4.0.1 on 2022-06-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_movee_lik_alter_pakage_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='komalji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailofk', models.EmailField(max_length=34443)),
                ('password', models.CharField(max_length=4553)),
            ],
        ),
    ]
