# Generated by Django 4.0.1 on 2022-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_komalji'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=678)),
                ('linkimg', models.CharField(max_length=45554646)),
                ('contactnum', models.CharField(max_length=45554646)),
            ],
        ),
    ]
