# Generated by Django 4.0.1 on 2022-06-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teams',
        ),
    ]
